import _ from "lodash"
export const BOOKING_STATUS_CREATED = "CREATED"
export const BOOKING_STATUS_CANCEL = "CANCEL"

export const BOOKING_STATUS = { BOOKING_STATUS_CREATED, BOOKING_STATUS_CANCEL }

export const BOOKING_STATUS_LIST = _.values(BOOKING_STATUS)
